Remote
marmelab/tipsy-symfony pull request #7
Opened 2021-01-28 16:05 UTC by guilbill

Deployment : Add docker-compose and deployment goals.

2021-01-28 17:50 UTC, zyhou approved these changes

2021-01-28 18:07 UTC, alexisjanvier requested changes
I didn't know the `git archive -o tipsy.zip HEAD` !
It's nice, however I'm not very convinced by this deployment. First of all, you have to zip it, send it and then dezip it, it's a bit ... long ? It seems to me that `rsync` would do the same thing at least more simply. It would also allow to put filters on what is transmitted to the server. Which brings me to the second point that bothers me: the `cp .env.prod .env`. 
So here, it's not a big deal yet because there is no secret information inside, but it's missing the symfony configuration mechanism. Indeed, there is a cascading logic of the configuration files (.env -> .env.[env] -> .env.[env].local) which allows to have the configuration corresponding to the execution environment only on the host machine. Here this mechanism is completely bypassed. 
It would be more correct to have a `.env.prod` (or a `.env.prod.local`) on the server, and inject an ENV=production to the docker compose.

2021-01-28 21:55 UTC, zyhou commented on Makefile
> +	rsync --delete -r -e "ssh -i ${key}" --filter=':- .gitignore' \
Wouah I like the `--filter` args

2021-01-29 07:35 UTC, alexisjanvier approved these changes

2021-01-29 07:35 UTC, merged